### ISSUE TITLE
Přidat do pravidel

### ISSUE THREAD

**Issue by vavraCZe** [vavraCZe/147#12]
Zákaz zacyklování spojů... Jako že dáte drátu k sobě a oni se spojí dohromady..

Taky nesmí být velký počet strojů u sebe...

Něco dalšího?

**Comment by vavraCZe** [comment]
To samé trubky... Když tedy postavíte stroje vedle sebe a trubky se propojí do sebe, tak je to porušení pravidel... Musíte je stavět ob jedno...

**Comment by merlin556** [comment]
a sakra "kladivo na nooby" :-D
