### ISSUE TITLE
zakázat canvas bag ID9268

### ISSUE THREAD

**Issue by merlin556** [vavraCZe/147#6]
Jdou jím duplikovat itemy da se cokoli dovnitr bag si hodis do listy otevres a ukazes mysi co chces zduplikovat a pri tom zmacknes cislo na kterym mas ten canvasbag v hotbaru... bag se posune na tom cisle bude zduplikovana vec a vevnitr puvodni zustane.

**Comment by vavraCZe** [comment]
Napiš mi sem ID, dík

**Comment by merlin556** [comment]
Vavro vavro to velky 9268 v nadpisu... :-D

**Comment by vavraCZe** [comment]
aj...

**Comment by vavraCZe** [comment]
MineTweaker Nenalezen, přidána alternativa DisableCraft a item byl zakázán...

**Comment by vavraCZe** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285901-1-6-4-forgeirc-v1-0-18-soul-shards-v2-0-15-and#reciperemover
